### ISSUE TITLE
need to fix this statement, and you have decided to enforce the yaml file ? won't be optional ? 

### ISSUE THREAD

**Issue by falloutats** [krutikatekwani26/data_processor#2]
https://github.com/krutikatekwani26/data_processor/blob/ec4da7227dfe92cb7e93e579205baf9d36b0f766/data_processor/core/dataset.py#L9C1-L10C1

**Comment by krutikatekwani26** [comment]
I am getting an error, if I do not provide the: `if schema_path else None`  statement right now. Its because `read_yaml` is not structured to handle that currently. I will change that and then that line can be removed. As of now I have enforced that the user will provide a yaml file for schema.
